name: Build resume and publish it on GitHub releases

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: release – ${{ github.ref_name }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Step 1.1 Download pdf artifact
        uses: actions/download-artifact@v2
        with:
          name: resume-pdf
          path: resume-pdf
      - name: Step 1.2 Download epub artifact
        uses: actions/download-artifact@v2
        with:
          name: resume-epub
          path: resume-epub
      - name: Step 2. Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            #### Changes in this Release

            - ${{ github.event.head_commit.message }}

            #### Download

            | PDF | EPUB |
            | --- | ---- |
            | <a href="https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/resume-andrelademann.pdf"><img width="144" src="https://cdn.githubraw.com/${{ github.repository }}/main/Content/Media/Cover/Cover-pdf.png" alt="Cover for pdf" /></a> | <a href="https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/resume-andrelademann.epub"><img width="144" src="https://cdn.githubraw.com/${{ github.repository }}/main/Content/Media/Cover/Cover-epub.png" alt="Cover for epub" /></a> |
            | [![Badge CV](https://img.shields.io/badge/Download_CV-100000?style=for-the-badge&logo=Adobe&logoColor=FFFFFF&labelColor=4E4796&color=DBD7FF)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/resume-andrelademann.pdf) | [![Badge Epub](https://img.shields.io/badge/Download_EPUB-100000?style=for-the-badge&logo=Adobe&logoColor=FFFFFF&labelColor=4E4796&color=DBD7FF)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/resume-andrelademann.epub) |
            
            ##### Download single files

            | Document     | Download |
            | ------------ | ---- |
            | Introduction | [![Badge CV](https://img.shields.io/badge/Download_CV-100000?style=for-the-badge&logo=Adobe&logoColor=FFFFFF&labelColor=4E4796&color=DBD7FF)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/andrelademann-introduction.pdf) | 
            | CV | [![Badge CV](https://img.shields.io/badge/Download_CV-100000?style=for-the-badge&logo=Adobe&logoColor=FFFFFF&labelColor=4E4796&color=DBD7FF)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/andrelademann-curriculum-vitae.pdf) | 
            | Portfolio | [![Badge CV](https://img.shields.io/badge/Download_CV-100000?style=for-the-badge&logo=Adobe&logoColor=FFFFFF&labelColor=4E4796&color=DBD7FF)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/andrelademann-portfolio.pdf) |
          draft: false
          prerelease: false

      - name: Step 3.1 Upload Introduction PDF Release Asset
        id: upload-release-asset-pdf-introduction
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./resume-pdf/andrelademann-introduction.pdf
          asset_name: andrelademann-introduction.pdf
          asset_content_type: application/pdf
      - name: Step 3.2 Upload CV PDF Release Asset
        id: upload-release-asset-pdf-cv
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./resume-pdf/andrelademann-curriculum-vitae.pdf
          asset_name: andrelademann-curriculum-vitae.pdf
          asset_content_type: application/pdf
      - name: Step 3.3 Upload Portfolio PDF Release Asset
        id: upload-release-asset-pdf-portfolio
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./resume-pdf/andrelademann-portfolio.pdf
          asset_name: andrelademann-portfolio.pdf
          asset_content_type: application/pdf


      - name: Step 4.1 Upload PDF Release Asset
        id: upload-release-asset-pdf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./resume-pdf/resume-andrelademann.pdf
          asset_name: resume-andrelademann.pdf
          asset_content_type: application/pdf
      - name: Step 4.2 Upload EPUB Release Asset
        id: upload-release-asset-epub
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./resume-epub/resume-andrelademann.epub
          asset_name: resume-andrelademann.epub
          asset_content_type: application/epub

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout sources
        uses: actions/checkout@v2
      - name: Step 2 - Create temporary folders
        run: |
          mkdir -p Results
          mkdir -p Temp
      - name: Step 3 - Generate the documents using Docker
        run: |
          ./Scripts/build.sh
      - name: Step 4.1 - Upload the PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume-pdf
          path: Results/resume-andrelademann.pdf
          if-no-files-found: error
          retention-days: 12
      - name: Step 4.2 - Upload the EPUB artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume-epub
          path: Results/resume-andrelademann.epub
          if-no-files-found: error
          retention-days: 12
